name: Build

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      buildType:
        description: "Build Type"
        required: false
        default: "MinSizeRel"
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

jobs:
  build:
    runs-on: windows-2022
    env:
      BUILD_TYPE: ${{ inputs.buildType }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Install conan
        run: pip install "conan>2.0"

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGTPROXY_BUILD_VERSION=${{github.run_number}}

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

      - name: Move program and binary
        run: |
          mkdir ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\src\${{env.BUILD_TYPE}}\*.exe ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\conan\build\*.dll ${{github.workspace}}\build\program

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gtproxy-${{github.sha}}
          path: ${{github.workspace}}\build\program
